name: Entrega Contínua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: api-go
        path: main

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} #KEY
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }} #END.IP
        REMOTE_USER: ${{ secrets.REMOTE_USER }} #NOME.USUARIO
        TARGET: /home/${{ secrets.REMOTE_USER }}


    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DBHOST }}
          export USER=${{ secrets.DBUSER }}
          export PASSWORD=${{ secrets.DBPASSWORD }}
          export NAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &